name: Patrick Whitehouse
markdown: kramdown
kramdown:
  auto_ids: false
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]
url: //patrickwhitehouse.github.io
permalink: /:title/
favicon: /images/favicon.ico
social:
  - platform: Twitter
    link: https://twitter.com/patrickdoesweb
  - platform: GitHub
    link: https://github.com/patrickwhitehouse
  - platform: Instagram
    link: https://instagram.com/p44adx

collections:
  - projects    