name: Patrick Whitehouse
markdown: kramdown
kramdown:
  auto_ids: false
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]
url: //patrickwhitehouse.github.io
permalink: /blog/:title:output_ext
hire-me: false